# Numpy quickstart

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# shape of array
a.shape

(3, 5)

In [4]:
# dimensions of arrays
a.ndim

2

In [5]:
# data type of array element
a.dtype.name

'int64'

In [6]:
# itemsize of array element
a.itemsize

8

In [7]:
# total number of element in array
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
# creating another array
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

### Array creation

In [13]:
import numpy as np

In [14]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

`array` transforms sequences of sequences into two-dimensional arrays, sequence of sequences of sequences into three-dimensional arrays, and so-on.

In [18]:
b = np.array([[1.5, 2, 3], (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [20]:
b.ndim, b.shape, b.itemsize, b.dtype, b.size

(2, (2, 3), 8, dtype('float64'), 6)

Specify the type of array explicitly at the runtime.

In [22]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

The function `zeros` creates an array full of zeroes.

In [23]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

The function `ones` creates an array full of ones.

In [24]:
np.ones([2, 3, 4], dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

The function `empty` creates an array whose initial content is random and depends on state of the memory. By default, the dtype of the created array is `float64`, but it can be specified via the keyword argument `dtype`.

In [25]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])