# Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- Numpy arrays have a fixed size at creation.
- The elements in a NumPy array are all required to be of the same data type, and thus will have the same size in the memory.
- NumPy arrays facilitate advanced mathematical and other types of operations on large number of data.

NumPy's array class is called `ndarray`. It is also known by the alias `array`. 

The more important attributes of an `ndarray` object are:

- **ndarray.ndim**
    The number of axes (dimensions) of the array.

- **ndarray.shape**
    the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with *n* rows and *m* columns, `shape` will `(n, m)`. This length of the `shape` tuple is therefore the number of axes, `ndim`.

- **ndarray.size**
    the total number of elements of the array. This is equal to the product of the elements of `shape`.

- **ndarray.dtype**
    - an object describing the type of the elements in the array.
 
- **ndarray.itemsize**
    - the size in bytes of each element of the array.

- **ndaray.data**
    the buffer containing the actual elements of the array.

In [3]:
import numpy as np

### Numpy Array creation

To create an array we are going to use the two function

1. `arange()`: It's used for creating array.
2. `reshape()`: This function is used for reshaping the array.

let's first create a numpy array.

In [4]:
a = np.arange(15).reshape(3, 5)

Now let's analyze what each function does. First `np.range()`

In [33]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

We obtain the array, but we don't what type of arary it is, let's use the python `type()` to find the type of the array. After running `type()` we get the type `numpy.ndarray`.

In [39]:
# To find the type of the 

type(arr)

numpy.ndarray

Not we will use the `reshape` function the change the shape of the numpy array.

In [46]:
arr.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

##### Attributes of numpy array

In [43]:
# To find the data type of the element in the numpy array
# we use the `dtype` attribute.
# or use dtype name `dtype.name`

print(a.dtype)
print(a.dtype.name)

int32
int32


In [40]:
# To find the shape of the numpy array
# we use the `shape` attribute.

a.shape

(3,)

In [41]:
# To find the dimensions of the numpy array.
# we the `ndim` array

a.ndim

1

In [44]:
# To find the size of item in the array,
# we use the `itemsize` attribute.

a.itemsize

4

In [11]:
# To find the total size of numpy array.
# use the `size` attribute

a.size

15

### Array Creation using Python `array` or `tuple`

You can create a numpy array from a regular Python list or tuple using the `array` function for numpy module. The type of resulting array type is deduced from the type of the elements in the sequences.

In [50]:
# creating an numpy array of integers, using the list of integers.

a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [51]:
# creating a numpy of floats,

b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

`array` transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [52]:
# 
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

# we have here used the integer and float in the input
# elements data type is automatically converted to `float`

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [54]:
# let supply the tuple of tuple as input

b = np.array(((1.5, 2, 3), (4, 5, 6)))
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

The type of array can also be explicitly specified at creation time:

In [57]:
# we can also given explicit data type at the time of creation.

c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

### Few function to create numpy array

##### Array of zeroes, 

the function `zeroes` creates an arary of zeroes

In [21]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##### Array of ones

the function `ones` creates an array full of ones.

In [22]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

##### The function `empty()` 

It creates an array whose intial content is random and depends on the state of memory. By default, the dtype of the created array is `float64`, but it can be specified via the key word argument `dtype`.

In [23]:

np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

##### Funciton `arange()`

We have seen the `arange()` function previously which is analogous to the Python built-in `range` but returns an array. Numpy `arange()` work the same way as python `range()` function. It accept the same argument as range, but additional numpy `arange()` function can also accept float argument.

In [58]:
# usage for arange()

np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [25]:
# usage arange() function using float values

np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When `arange()` is used with floating points arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function `linspace` that receives as an argument the number of elements that we want, instead of the step.

In [26]:
from numpy import pi

# 9 numbers from 0 to 2
np.linspace(0, 2, 9)            

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [27]:
# useful to evaluate function a lots of points

# the following generate 100 numbers between 0 and 6.28 (2 * pi) or (2 * 3.14)
x = np.linspace(0, 2 * pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [28]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -