In [1]:
import numpy as np

**One-dimensional** arras can be indexed, sliced and iterated over, much like lists, and other python sequences.

In [17]:
# create a array

a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [5]:
# accesing element at index 2

a[2]

8

In [6]:
# access element between index 2 and 5
a[2:5]

array([ 8, 27, 64])

In [10]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [11]:
# reversing numpy array "a"
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [13]:
# itertaing over the numpy array with for loop
for i in a:
    print(i)

1000
1
1000
27
1000
125
216
343
512
729


In [16]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


**Multidimensional** arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [18]:
def f(x, y):
    return 10 * x + y

In [19]:
# creating numpy array using callable function all
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [26]:
# second example of creating numpy array using function call.

def f2(x, y):
    return x+y
c = np.fromfunction(f2, (5, 4), dtype=int)
c

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [28]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [29]:
# accessing fourth element from third row
b[2, 3]

23

In [31]:
# accessing each row in the second column of b
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [33]:
# accessing second element from each row
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [38]:
# each column in the second and third row of b
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided then the number of axes, the missing indices are considered complete slices:

In [40]:
# the last row. Equivalent to b[-1, :]
b[-1]

array([40, 41, 42, 43])

The expression within brackets in `b[i]` is treated as an `i` followed by as many instances of `:` as needed to represent the remaining axes. NumPy also allows you to write this using dots as `b[i, ...]`.

The **dots** (`...`) represent as many colons are needed to produce a complete indexing tuple. For example, if `x` is an array with 5 axes, then

- x[1, 2, ...]` is equivalent to `x[1, 2, :, :, :]`
- `x[..., 3]` to `x[:, :, :, :, 3]` and
- `x[4, ..., 5, :]` to `x[4, :, :, 5, :]`.

In [45]:
# to access second element from all rows,
# using dot notation
b[..., 1]

array([ 1, 11, 21, 31, 41])

In [49]:
# a 3D array (two stacked 2D arrays)
c = np.array([[[0, 1, 2],
               [10, 12, 13]],
             [[100, 101, 102],
              [110, 112, 113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [51]:
c.shape

(2, 2, 3)

In [53]:
# same as c[1, :, :] or c[1]
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [55]:
# same as c[:, :, 2]
c[..., 2]

array([[  2,  13],
       [102, 113]])

**Iterating** over multidimensional arrays is done with respect to the first axis:

In [56]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operation on each element in the array, one can uses the `flat` attribute which is an iterator over all the elements of the array:

In [57]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
