In [19]:
import numpy as np
import secrets

In [20]:
rg = np.random.default_rng(1)

Severals arrays can be stacked together along.

Let's suppose we have two ndarray `a` and `b`, and we have to stack them vertical on those on top of one another.

First of all we are going to create our arrays `a` and `b`, after that we have to use the `ndarray.vstack` function, to stack them vertically.

In [21]:
a = np.floor(10 * rg.random((2, 2)))
a

array([[5., 9.],
       [1., 9.]])

In [22]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[3., 4.],
       [8., 4.]])

In [23]:
# stacking "a" and "b" vertically
np.vstack((a, b))

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.]])

Now we are going to stack them horizontally.

In [24]:
# stacking "a" and "b" horizontally
np.hstack((a, b))

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

#### numpy.floor()

This function return the floor of the input, element-wise.

The floor of the scalar x is the largest integer *i*, such that *i<=x*.



Some spreadsheet programs calculate the “floor-towards-zero”, where floor(-2.5) == -2. NumPy instead uses the definition of **floor** where *floor*(-2.5) == -3. The “floor-towards-zero” function is called `fix` in NumPy.

In [25]:
afloor = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

In [26]:
np.floor(afloor)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

There are other function such as `column_stack` stacks 1D arrays as columns into a 2D array. It is equivalent to `hstack` only for 2D arrays:

In [27]:
from numpy import newaxis

In [29]:
# with 2D arrays
np.column_stack((a, b))

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

In [41]:
a = np.array([4., 2.])
b = np.array([3., 8.])

In [42]:
a, b

(array([4., 2.]), array([3., 8.]))

In [43]:
# returns a 2D array
np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [44]:
# the result is different
np.hstack((a, b))

array([4., 2., 3., 8.])