In [1]:
import numpy as np
import secrets

In [2]:
rg = np.random.default_rng(1)

Severals arrays can be stacked together along.

Let's suppose we have two ndarray `a` and `b`, and we have to stack them vertical on those on top of one another.

First of all we are going to create our arrays `a` and `b`, after that we have to use the `ndarray.vstack` function, to stack them vertically.

In [3]:
a = np.floor(10 * rg.random((2, 2)))
a

array([[5., 9.],
       [1., 9.]])

In [4]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[3., 4.],
       [8., 4.]])

In [5]:
# stacking "a" and "b" vertically
np.vstack((a, b))

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.]])

Now we are going to stack them horizontally.

In [6]:
# stacking "a" and "b" horizontally
np.hstack((a, b))

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

### numpy.floor()

This function return the floor of the input, element-wise.

The floor of the scalar x is the largest integer *i*, such that *i<=x*.



Some spreadsheet programs calculate the “floor-towards-zero”, where floor(-2.5) == -2. NumPy instead uses the definition of **floor** where *floor*(-2.5) == -3. The “floor-towards-zero” function is called `fix` in NumPy.

In [7]:
afloor = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

In [8]:
np.floor(afloor)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

### np.column_stack()

There are other function such as `column_stack` stacks 1D arrays as columns into a 2D array. It is equivalent to `hstack` only for 2D arrays:

In [9]:
from numpy import newaxis

In [10]:
# with 2D arrays
# 
# stacking 2D arrays, similar to `hstack`

np.column_stack((a, b))

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

In [11]:
# will get the same result as above
# similar to 2D arrays, with `column_stack`

np.hstack((a, b))

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

In [12]:
# but for 1D array, `column_stack` will
# stack them vertically, and return a 2D arrays

a = np.array([4., 2.])
b = np.array([3., 8.])
a, b

(array([4., 2.]), array([3., 8.]))

In [13]:
# `column_stack` will returns a 2D array,
# 1D arrays are stack vertically returning 2D array.

np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [14]:
# but, `hstack` will align 1D arrays horizontally
# the result is different

np.hstack((a, b))

array([4., 2., 3., 8.])

On the other hand, the function `row_stack` is equivalent to `vstack` for any input arrays. In fact, `row_stack` is in alias for `vstack`:

In [15]:
# whereas `hstack` is not an alias to `column_stack`

np.column_stack is np.hstack

False

In [16]:
# `vstack` is an alias to `row_stack`

np.row_stack is np.vstack

True

In [17]:
a, b

(array([4., 2.]), array([3., 8.]))

In [18]:
# using `row_stack` on above arrays

np.row_stack((a, b))

array([[4., 2.],
       [3., 8.]])

In [19]:
# using `vstack` on above arrays on comparing them
# with `row_stack`

np.vstack((a, b))

array([[4., 2.],
       [3., 8.]])