In [21]:
from numpy import newaxis
import numpy as np

### numpy.newaxis

A convenient alias for None, usefull for indexing arrays.

In [22]:
newaxis is None

True

In [23]:
x = np.arange(3)
x

array([0, 1, 2])

In [24]:
x[:, newaxis]

array([[0],
       [1],
       [2]])

In [25]:
x[:, newaxis, newaxis]

array([[[0]],

       [[1]],

       [[2]]])

In [26]:
x[:, newaxis] * x

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

Let try to use `newaxis` with `column_stack` and `row_stack`

In [27]:
x = np.arange(3)
y = np.arange(3)
x, y

(array([0, 1, 2]), array([0, 1, 2]))

In [37]:
x[:, newaxis], y[:, newaxis]

(array([[0],
        [1],
        [2]]),
 array([[0],
        [1],
        [2]]))

In [36]:
cstk = np.column_stack((x, y))
cstk, cstk.shape

(array([[0, 0],
        [1, 1],
        [2, 2]]),
 (3, 2))

In [38]:
cstk2 = np.column_stack((x[: newaxis], y[:, newaxis]))
cstk2, cstk2.shape

(array([[0, 0],
        [1, 1],
        [2, 2]]),
 (3, 2))

In [33]:
rstk = np.row_stack((x, y))
rstk, rstk.shape

(array([[0, 1, 2],
        [0, 1, 2]]),
 (2, 3))

In [35]:
rstk2 = np.row_stack((x[:, newaxis], y[:, newaxis]))
rstk2, rstk2.shape

(array([[0],
        [1],
        [2],
        [0],
        [1],
        [2]]),
 (6, 1))

Outer product, same as `outer(x, y)`:

In [41]:
x = np.arange(3)
y = np.arange(3, 6)

In [43]:
x[:, newaxis] * y

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [ 6,  8, 10]])

`x[newaxis, :]` is equivalent to `x[newaxis]` and `x[None]`:

In [44]:
x[newaxis, :].shape

(1, 3)