In [3]:
import numpy as np

In [4]:
rg = np.random.default_rng()

# Splitting one array into several smaller ones

### Split



Split an array into multiple sub-arrays as views into array.

**Syntax** 

```py
numpy.split(array, indices_or_sections, axis=0)
```

#### Parameters:

**array**: ***ndarray***

- Array to be divided into sub-arrays

**indices_or_sections** : ***int or 1-D array***

- If *indices_or_sections* is an integer, N, the array will be divided into N equal arrays along *axis*. If such a split is not possible, an error is raised.
- If *indices_or_sections* is a 1-D array of sorted integers, the entries indicate where along axis the array is split. For example, `[2, 3]`, would, for `axis=0`, result in
    - `array[:2]`
    - `array[2:3]`
    - `array[3:]`
- If an index exceeds the dimension of the array along *axis*, an empty sub-array is returned correspondingly.


**axis**: ***int, optional***

- The axis along which to split, default is 0.


#### Returns

**sub-arrays**: ***list of ndarrays***

- A list of sub-arrays as views into array.

#### Raises

**ValueError**

- If *indices_or_sections* is given as an integer, but a split does not result in equal division.


In [28]:
x = np.arange(9.0)

In [30]:
# Split the array in 3 equal parts

np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [31]:
# Split the array on 1-D ndarray

np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7., 8.]),
 array([], dtype=float64)]

### Horizontal Split

Using `hsplit`, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifing the columns after which the division should occur:

In [6]:
a = np.floor(10 * rg.random((2, 12)))

In [8]:
a

array([[6., 4., 8., 3., 1., 5., 1., 4., 9., 9., 9., 5.],
       [9., 9., 6., 8., 7., 0., 4., 1., 7., 8., 6., 0.]])

In [9]:
# Split `a` into 3

np.hsplit(a, 3)

[array([[6., 4., 8., 3.],
        [9., 9., 6., 8.]]),
 array([[1., 5., 1., 4.],
        [7., 0., 4., 1.]]),
 array([[9., 9., 9., 5.],
        [7., 8., 6., 0.]])]

In [11]:
# Split `a` after the third and forth column

np.hsplit(a, (3, 4))

[array([[6., 4., 8.],
        [9., 9., 6.]]),
 array([[3.],
        [8.]]),
 array([[1., 5., 1., 4., 9., 9., 9., 5.],
        [7., 0., 4., 1., 7., 8., 6., 0.]])]

### Vertical Split

Split an array into multiple sub-arrays vertically (row-wise).

`vsplit` is equivalent to `split` with *axis=0* (default), the array is always split along the first axis regardless of the array dimension.

In [15]:
array = np.floor(10 * rg.random((4, 4)))

In [16]:
array

array([[0., 6., 0., 5.],
       [6., 1., 7., 8.],
       [1., 2., 1., 8.],
       [9., 8., 3., 1.]])

In [18]:
# spliting the array vertically in 2

np.vsplit(array, 2)

[array([[0., 6., 0., 5.],
        [6., 1., 7., 8.]]),
 array([[1., 2., 1., 8.],
        [9., 8., 3., 1.]])]

In [21]:
# splitting the another array

np.vsplit(array, np.array([3, 6]))

[array([[0., 6., 0., 5.],
        [6., 1., 7., 8.],
        [1., 2., 1., 8.]]),
 array([[9., 8., 3., 1.]]),
 array([], shape=(0, 4), dtype=float64)]