In [2]:
import numpy as np
import secrets

# Shape Manipulation

### Changing the shape of an array

An array has a shape given by the number of elements along each axis:

In [3]:
rg = np.random.default_rng(1)

In [5]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [6]:
a.shape

(3, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [8]:
# returns the array, flattened
a.ravel()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [9]:
# returns the array with a modified shape
a.reshape(6, 2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [10]:
# returns the array, tranposed
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [11]:
# check the shape of transposed matrix
print(a.T.shape)

(4, 3)


In [12]:
# checking shape of original matrix 
print(a.shape)

(3, 4)


The `reshape` function returns its argument with a modified shape, wherea's the `ndarray.resize` method modifies the array itself:

In [13]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [14]:
# ndarray.resize() method modifies the array itself.
a.resize((2, 6))

In [15]:
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

If a dimension is given as `-1` in a reshaping operation, the other dimensions are automaticaly calculated:

In [16]:
a.reshape(3, -1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])