In [76]:
import numpy as np

In [77]:
rg = np.random.default_rng()

# Copies and Views

### No Copy at All

Simple assignments make no copy of objects or their data.

In [78]:
a = np.array(
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]
    ]
)

In [79]:
# no new object is created
b = a

In [80]:
# a and b are two names for the two ndarray object
b is a

True

Python passes mutable objects as references, so function calls make no copy

In [81]:
def f(x):
    print(id(x))

In [82]:
# id is a unique identifier of an object
id(a)

140016736843216

In [83]:
f(a)

140016736843216


### View or Shallow Copy

Different array objects can share the same data. 

The `view` method creates a new array object that looks at the same data.

In [84]:
# a = np.arange(15).reshape(3, 5)

In [85]:
c = a.view()

In [86]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
c is a

False

In [88]:
# c is view of the data owned by a

c.base is True

False

In [89]:
# a's shape doesn't change

c = c.reshape((2, 6))
c.shape

(2, 6)

In [90]:
a.shape

(3, 4)

In [91]:
# a's data doesn't change

c[0, 4] = 1234
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [92]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Slicing an array returns a view of it:

In [93]:
s = a[:, 1:3]
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [94]:
# s[:] is a view of s.

s[:] = 10
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [95]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

### Deep Copy

The `copy` method makes a complete copy of the array and its data.

In [96]:
# a new array object with new data is created.

d = a.copy()

In [97]:
d is a

False

In [98]:
# d doesn't share anything with a

d.base is a

False

In [99]:
d[0, 0] = 9999

In [100]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

Sometimes `copy` should be called after slicing if the original array is not required anymore.

For example, suppose `a` is a huge intermidate result and the final result `b` only contains a small fraction of `a`, a deep copy should be made when constructing `b` with slicing:

In [101]:
a = np.arange(int(1e8))
a

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [103]:
b = a[:100].copy()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [104]:
# delet the memory of a

del a

If `b = a[:100]` is used instead, `a` is referenced by `b` and will persist in memory even if `del a` is executed.