# Numpy

NumPy (**Numerical Python**) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.

NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development.

The NumPy API is used extensively in *Pandas*, *SciPy*, *Matplotlib*, *scikit-learn*, *scikit-image* and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it.

NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

### Install the NumPy

```sh
$ pip install numpy
```

### Import NumPy

```py
import numpy as np
```

In [3]:
import numpy as np

### Difference between NumPy and Python list

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.


#### Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.


### How to create a basic NumPy array?

To create a NumPy array using Python list, `np.array()` function is used

In [4]:
a = np.array([1, 2, 3])

In [5]:
a

array([1, 2, 3])

Creating an array filled with `0`'s, for this `np.zeros()` function is used:

In [6]:
np.zeros(2)

array([0., 0.])

Creating a array filled with `1`'s, for this `np.ones()` function is used:

In [7]:
np.ones(2)

array([1., 1.])

#### np.empty()

The `empty` function creates an array whose initial content is random and depends on the state of the memory. You can use `empty` over `ones`, because of speed - elements can be filled after the array initialization:

In [10]:
# Create an empty array with 2 elements

np.empty(2)

array([1., 1.])

You can create a elements with a range of elements:

In [11]:
np.arange(4)

array([0, 1, 2, 3])

And even an array that contains a range of event spaced intervals. To do this, you will specify the **first number**, **last number** and **step size**.

In [12]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

You can also use `np.linespace()` to create an array with values that are spaced linearly in a spaced interval:

In [15]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### Specifying your data type

While the default data type is floating point (`np.float64`), you can explicitly specify which data type you want using the `dtype` keyword.

In [18]:
# default data type is `float64`

np.ones(2)

array([1., 1.])

In [17]:
# create an array of `int16`

x = np.ones(2, dtype=np.int16)
x

array([1, 1], dtype=int16)