# Numpy quickstart

### Ojective

- Understand the difference between, one-, two- and n- dimensional arrays in NumPy.
- Understand the how to apply some linear algebra operations to n-dimensional arrays without using for-loops.
- Understanding axis and shape properties for n-dimensional arrays.

# The basics

Let's take an example to understand the basics attributes of NumPy array. Let's create an array of 15 element from 0 to 14, in having shape (3,5) (here, shape in simple term refer to matrix dimensional).

In [2]:
# import numpy
import numpy as np

# creating a numpy array
nparray = np.arange(15).reshape(3, 5)
nparray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

When we create a array using NumPy, we get the returned object as `ndarray`. Note that `numpy.array` is nto the same as the standard python library class `array.array`, which only handles one-dimensional arrays and offers less functionality. Let's check the type of `nparray` variable.

In [3]:
type(nparray)

numpy.ndarray

As you can see the returned object is `numpy.ndarray`. This `ndarray` provides some attributes which you can use to get to know or to get information on your array. We are going to see the array one at a time.

1. **ndarray.ndim**: the number of axes (dimensions) of the array.
2. **ndarray.shape**: The dimensions of the array. This is tuple of integers indicating the size of the array in each dimension.
3. **ndarray.size**: the total number of elements of  the array. This is equal to the product of the elements of the `shape`.
4. **ndarray.dtype**: an object describing the type of the elements in the array.
5. **ndarray.itemsize**: The size in bytes of each element of the array.
6. **ndarray.data**: the buffer containing the acutal elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [4]:
# shape of ndarray
nparray.shape

(3, 5)

In [5]:
# size of ndarray
nparray.size

15

In [6]:
# dimensional of ndarray
nparray.ndim

2

In [7]:
# datatype of ndarray
nparray.dtype

dtype('int32')

In [8]:
# itemsize of ndarray
nparray.itemsize

4

In [9]:
# data of ndarray
nparray.data

### Array creation

We have already seen an example of creating a numpy array using, `arange` function, and then we have used `reshape` function to reshape the array. Let's explore some ways to create arrays.

#### 1. `np.array`

This functions takes Python list (or tuple) as an input, and create an `ndarray` of  elements from the input object. Lets see an example using the Python list:

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

using Python tuple:

In [14]:
arr = np.array((1, 2, 3, 4, 5, 6))
arr

array([1, 2, 3, 4, 5, 6])

Since returned object is an `ndarray`, we can apply the same attributes as we have used above to get info on the array. We can also create multi-dimensional array using `np.array`, for that we have to give input as Python nested lists or nested tuple or combination of nested list and tuple.

In [17]:
mdim_arr = np.array([[1, 2], [2, 3]])
mdim_arr

array([[1, 2],
       [2, 3]])

In the multiple dimensional array also we have all the basic attributes. Lets check the shape of array, rest of them you try it:

In [18]:
mdim_arr.shape

(2, 2)

NumPy arrays also support other numeric types such as *floating point* and *complex type*. Lets create an array of floating type:

In [19]:
# creating a float types array
f = np.array([[2.3, 2.1], [3.1, 3.2]])
f

array([[2.3, 2.1],
       [3.1, 3.2]])

In [20]:
# data types
f.dtype

dtype('float64')

If you try to creating mix type array using, *float* and *integer*, the numpy will convert all the item to *float*, because in python *floating points* have higher precedence. Take a look at this example:

In [21]:
mt = np.array([1, 1.2, 3, 4])
mt

array([1. , 1.2, 3. , 4. ])

In [22]:
mt.dtype

dtype('float64')