In [2]:
import numpy as np

### Reshaping the array.

Reshape function is used for reshaping the array.

In [3]:
# 1d array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [4]:
# 2d array
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
# 3d array
c = np.arange(24).reshape(2,3,4)

### Arithmetic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [6]:
# creating two array.
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [7]:
# subraction performed on the array
c = a - b 
c

array([20, 29, 38, 47])

In [8]:
# exponential performed on array
b ** 2

array([0, 1, 4, 9])

In [9]:
# using sin() on array `a`
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [10]:
# checking all value less than 35 in `a`
a < 35

array([ True,  True, False, False])

The product operator `*` operators elementwise in NumPy arrays.

In [11]:
A = np.array([[1, 1,], [0, 1]])

In [12]:
B = np.array([[2, 0], [3, 4]])

In [13]:
A * B

array([[2, 0],
       [0, 4]])

The matrix product can be erformaed using the `@` operator

In [14]:
A @ B

array([[5, 4],
       [3, 4]])

matrix using `dot()` funcion.

In [15]:
A.dot(B)

array([[5, 4],
       [3, 4]])

Some operations, such as `+=` and `*=`, act in place to modify an existing array rather than create a new one.

In [16]:
# create instance of default random number generator.
# using which we will generate numpy array of random element.

rg = np.random.default_rng(1)

In [17]:
# generating numpy array of ones with shape (2, 3)

a = np.ones((2, 3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
# now we will generate a random numpy array of shape (2, 3)

b = rg.random((2, 3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [21]:
# multiplying 3 to the ones array.
# therefore all the elements will get mutiple by  3
# without returning new array

a *= 3
a

array([[9, 9, 9],
       [9, 9, 9]])

In [20]:
# added 3 to the array
# therefore all the elements will be increased by 3
# with out returning new array

b += 3
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

### Unary operations

Operations such as computing the sum of all elements in the array, are implemeneted as methods in the `ndarray` class.

Suppose we have the a random numpy array of shape (2, 3)

In [22]:
rg = np.random.default_rng(1)

In [24]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

To find the all of all element we use `sum()` method

In [25]:
a.sum()

3.1057109529998157

and to find minimun and maximum values, we use `min()` and `max()` method.

In [26]:
a.min()

0.027559113243068367

In [27]:
a.max()

0.8277025938204418

By default, these operations, apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the `axis` parameter you can apply an operation along the specified axis of an array:

In [29]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
# sum of each column

b.sum(axis=0)

array([12, 15, 18, 21])

In [32]:
# min of each row

b.min(axis=1)

array([0, 4, 8])

In [34]:
# cumulative sum along each row

b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])