In [2]:
import numpy as np

### Reshaping the array.

Reshape function is used for reshaping the array.

In [6]:
# 1d array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [5]:
# 2d array
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
# 3d array
c = np.arange(24).reshape(2,3,4)

### Arithmetic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [18]:
# creating two array.
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [15]:
# subraction performed on the array
c = a - b 
c

array([20, 29, 38, 47])

In [16]:
# exponential performed on array
b ** 2

array([0, 1, 4, 9])

In [17]:
# using sin() on array `a`
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [19]:
# checking all value less than 35 in `a`
a < 35

array([ True,  True, False, False])

The product operator `*` operators elementwise in NumPy arrays.

In [20]:
A = np.array([[1, 1,], [0, 1]])

In [21]:
B = np.array([[2, 0], [3, 4]])

In [22]:
A * B

array([[2, 0],
       [0, 4]])

The matrix product can be erformaed using the `@` operator

In [23]:
A @ B

array([[5, 4],
       [3, 4]])

matric using `dot()` funcion.

In [24]:
A.dot(B)

array([[5, 4],
       [3, 4]])

Some operations, such as `+=` and `*=`, act in place to modify an existing array rather than create a new one.

In [25]:
# create instance of default random number generator.
rg = np.random.default_rng(1)

In [31]:
a = np.ones((2, 3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
b = rg.random((2, 3))
b

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [29]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [30]:
b += 3
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])