# Table of content

- Sparse matrix representation
    - [CSR](#csr-representation)
    - [DOK](#dok-representation)
    - [LIL](#lil-representation)


# A simple, sparse matrix

A simple, sparse matrix will be constructed to show the representation formats of a sparse matrix in Python.

In [16]:
import numpy as np
from scipy import sparse

In [17]:
X = np.array([[0,0,0,3,0,0,4],
              [0,5,0,0,0,0,0],
              [0,0,5,0,0,4,0],
              [4,0,0,0,0,0,1],
              [0,2,0,0,3,0,0]])
print(X)

[[0 0 0 3 0 0 4]
 [0 5 0 0 0 0 0]
 [0 0 5 0 0 4 0]
 [4 0 0 0 0 0 1]
 [0 2 0 0 3 0 0]]


There's many zeros in this matrix, so let's calculate the sparsity of the matrix:

In [18]:
sparsity = 1.0 - (np.count_nonzero(X) / X.size)
print("The sparsity of X is ", sparsity)

The sparsity of X is  0.7428571428571429


### CSR representation


We can convert  this **dense** matrix into a sparse matrix by using the `sparse.csr_matrix()` function. The row/column indices of nonzero values are stored in a *Compressed Sparse Row (CSR)* matrix:

In [19]:
# Convert X to a sparse Matrix

S1 = sparse.csr_matrix(X)

print(f"""
Type of sparse matrix representation: {type(S1)}

Sparse Matrix:\n{S1}

Sparse Data: {S1.data}

Indices of columns: {S1.indices}

Pointers for data: {S1.indptr}
""")


Type of sparse matrix representation: <class 'scipy.sparse._csr.csr_matrix'>

Sparse Matrix:
  (0, 3)	3
  (0, 6)	4
  (1, 1)	5
  (2, 2)	5
  (2, 5)	4
  (3, 0)	4
  (3, 6)	1
  (4, 1)	2
  (4, 4)	3

Sparse Data: [3 4 5 5 4 4 1 2 3]

Indices of columns: [3 6 1 2 5 0 6 1 4]

Pointers for data: [0 2 3 5 7 9]



### DOK representation

Another efficient structure for constructing sparse matrices is the **Dictionary of Keys (DOK)**, where a python dictionary is used to represent non-zero values of sparse matrix.

In this representation, `keys()` is used for indices, and `values()` is used for values of non-zero elements:

In [20]:
S2 = sparse.dok_matrix(X)

print(f"""
Type of sparse matrix representation: {type(S2)}

Sparse Matrix:\n{S2}

Keys in dictionary: {S2.keys()}

Values in dictionary: {S2.values()}
""")


Type of sparse matrix representation: <class 'scipy.sparse._dok.dok_matrix'>

Sparse Matrix:
  (0, 3)	3
  (0, 6)	4
  (1, 1)	5
  (2, 2)	5
  (2, 5)	4
  (3, 0)	4
  (3, 6)	1
  (4, 1)	2
  (4, 4)	3

Keys in dictionary: dict_keys([(0, 3), (0, 6), (1, 1), (2, 2), (2, 5), (3, 0), (3, 6), (4, 1), (4, 4)])

Values in dictionary: dict_values([3, 4, 5, 5, 4, 4, 1, 2, 3])



### LIL representation

The Last representation format shown here is a row-based **list of lists sparse (LIL)** matrix. The first list stores column indices for each row, and the second list is used to store the element's row values.

In [21]:
S3 = sparse.lil_matrix(X)

print(f"""
Type of sparse matrix representation: {type(S3)}

Sparse Matrix:\n{S3}

Lists for rows: {S3.rows}

Lists for columns: {S3.data}
""")


Type of sparse matrix representation: <class 'scipy.sparse._lil.lil_matrix'>

Sparse Matrix:
  (0, 3)	3
  (0, 6)	4
  (1, 1)	5
  (2, 2)	5
  (2, 5)	4
  (3, 0)	4
  (3, 6)	1
  (4, 1)	2
  (4, 4)	3

Lists for rows: [list([3, 6]) list([1]) list([2, 5]) list([0, 6]) list([1, 4])]

Lists for columns: [list([3, 4]) list([5]) list([5, 4]) list([4, 1]) list([2, 3])]



In `scipy.sparse` package, there is also a `todense()` function for converting a sparse matrix to a dense matrix:

In [22]:
# Convert the sparse matrix to a dense matrix

X  = S1.todense()

print(X)

[[0 0 0 3 0 0 4]
 [0 5 0 0 0 0 0]
 [0 0 5 0 0 4 0]
 [4 0 0 0 0 0 1]
 [0 2 0 0 3 0 0]]


This can be useful when exploring data, but if your dataset is large, the dense matrix won't fit in memory and may cause an error.

# Sparse Matrix from a real dataset

In [23]:
from sklearn.datasets import fetch_20newsgroups

In [24]:
newsgroups_train = fetch_20newsgroups(subset='train', categories= ['sci.electronics', 'sci.space'])


In [25]:
newsgroups_train.data[0]

"From: cab@col.hp.com (Chris Best)\nSubject: Re: Food Dehydrators\nOrganization: your service\nLines: 10\nDistribution: usa\nNNTP-Posting-Host: hpctdkz.col.hp.com\n\n>   Does anybody out there have one of those food dehydrators I've been seeing\n> all over late-night TV recently? I was wondering if they use forced air, heat,\n> or both. If there's heat involved, anybody know what temperature they run at?\n> My wife would like one and I'm not inclined to pay >$100.00 for a box, a fan\n> and a heater. Seems to me you should be able to throw a dehydrator together\n> for just a few bucks. Heck, the technology is only what? 1,000 years old?\n\n----------\n\nYeah, but 1000 years ago, you couldn't buy it from a guy with sprayed-on hair!\n"

Use `CountVectorizer` to vectorize the text into a term-document matrix:

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
cv = CountVectorizer()

In [28]:
cv.fit(newsgroups_train.data)

CountVectorizer()

In [29]:
# Create a term-document matrix
word_matrix = cv.transform(newsgroups_train.data)

In [30]:
print(f'Type of the matrix is: {type(word_matrix)}\n')

print(f'Matrix:\n{word_matrix}')

Type of the matrix is: <class 'scipy.sparse._csr.csr_matrix'>

Matrix:
  (0, 0)	1
  (0, 1)	1
  (0, 187)	1
  (0, 188)	1
  (0, 189)	1
  (0, 3013)	1
  (0, 3387)	1
  (0, 3424)	1
  (0, 3502)	1
  (0, 3688)	2
  (0, 3794)	2
  (0, 4144)	1
  (0, 4514)	1
  (0, 4557)	1
  (0, 4650)	1
  (0, 4936)	1
  (0, 4962)	1
  (0, 5127)	1
  (0, 5225)	1
  (0, 5234)	1
  (0, 5360)	1
  (0, 5912)	1
  (0, 6180)	2
  (0, 6237)	2
  (0, 6822)	1
  :	:
  (1183, 20345)	1
  (1183, 20370)	1
  (1183, 20381)	1
  (1183, 20386)	1
  (1183, 20398)	2
  (1183, 20416)	1
  (1183, 20509)	1
  (1183, 20548)	11
  (1183, 20975)	1
  (1183, 21002)	2
  (1183, 21077)	2
  (1183, 21224)	1
  (1183, 21305)	1
  (1183, 21344)	3
  (1183, 21345)	2
  (1183, 21358)	1
  (1183, 21541)	1
  (1183, 21892)	1
  (1183, 22075)	1
  (1183, 22096)	1
  (1183, 22139)	1
  (1183, 22233)	2
  (1183, 22318)	3
  (1183, 22347)	1
  (1183, 22478)	5


In [31]:
print(f'Size of the matrix is: {word_matrix.shape}')

Size of the matrix is: (1184, 22577)


In [32]:
print(f'Number of the Non-zero values: {word_matrix.nnz}')

Number of the Non-zero values: 174709


We calculate the sparsity:

In [33]:
sparsity = word_matrix.nnz / (word_matrix.shape[0] * word_matrix.shape[1])

print("Sparsity value: ", sparsity)

Sparsity value:  0.006535778758339329


Convert a sparse matrix to a dense matrix

In [34]:
D = word_matrix.todense()
print(D)

[[1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 2 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


With the dense version we can calculate the proportion of space saved by sparse matrix representation:

In [35]:
r = 1 - (3 * np.count_nonzero(D)) / D.size

print("The proportion of saved space is ", r)

The proportion of saved space is  0.980392663724982
